name: 🚀 Deploy Swell Child Theme to Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to staging
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.STAGING_FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USERNAME }}
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          # server-dir: public_html/dev/wp-content/themes/
          # server-dir: wp-content/themes/
          server-dir: wp-content/themes/swell_child/
          local-dir: ./wp-content/themes/swell_child/
          protocol: ftp
          # fail-on-error: true
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/node_modules/**
